services:
  redis:
    image: redis:7-alpine
    container_name: gasoprice-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  backend:
    build: .
    container_name: gasoprice-backend
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped
